{
 "cells": [
  {
   "cell_type": "code",
   "execution_count": 7,
   "id": "207f96c4",
   "metadata": {},
   "outputs": [],
   "source": [
    "import os\n",
    "import time\n",
    "import json\n",
    "import math\n",
    "import pickle\n",
    "import requests\n",
    "import pandas as pd\n",
    "import numpy as np\n",
    "import yfinance as yf\n",
    "import pytz\n",
    "\n",
    "from datetime import datetime, timedelta\n",
    "from pandas.tseries.offsets import BMonthEnd\n",
    "from dateutil.relativedelta import relativedelta\n",
    "\n",
    "from sklearn.linear_model import LinearRegression\n",
    "import scipy.stats as stats\n",
    "import bs4 as bs\n",
    "\n",
    "from openpyxl import Workbook, load_workbook\n",
    "from openpyxl.drawing.image import Image\n",
    "import xlsxwriter\n",
    "import plotly\n",
    "import plotly.express as px\n",
    "import matplotlib.pyplot as plt\n",
    "import seaborn as sns"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": 8,
   "id": "b87bc253",
   "metadata": {},
   "outputs": [
    {
     "name": "stdout",
     "output_type": "stream",
     "text": [
      "Found 1 tickers: CVI\n",
      "\n",
      "==============================\n",
      "🚀 Processing ticker: CVI\n",
      "==============================\n",
      "CVI: Income Statement retrieved (20 quarters).\n",
      "CVI: ⏳ Rate limit hit on BALANCE_SHEET, waiting 20s... (Attempt 1)\n",
      "CVI: Balance Sheet retrieved (20 quarters).\n",
      "CVI: ⏳ Rate limit hit on CASH_FLOW, waiting 20s... (Attempt 1)\n",
      "CVI: Cash Flow Statement retrieved (20 quarters).\n",
      "CVI: ✅ Financial Data saved to /Users/andras/OneDrive/Fundamentals/MoreComp/Comp/df_CVI.xlsx\n",
      "CVI: ⏳ Rate limit hit on OVERVIEW, waiting 12s... (Attempt 1)\n",
      "CVI: 🏢 Company Data saved to /Users/andras/OneDrive/Fundamentals/MoreComp/CD/CD_CVI.xlsx\n"
     ]
    }
   ],
   "source": [
    "# ===========================\n",
    "# PATH CONFIG (GITHUB SAFE)\n",
    "# ===========================\n",
    "\n",
    "BASE_PATH = \"./data\"\n",
    "OUTPUT_PATH = os.path.join(BASE_PATH, \"Comp\")\n",
    "COMP_PATH = os.path.join(BASE_PATH, \"CD\")\n",
    "TICKERS_FILE = \"./tickers.txt\"\n",
    "\n",
    "API_KEY = '5VJ5OHNNB582TWUU'\n",
    "\n",
    "STATEMENTS = {\n",
    "    'INCOME_STATEMENT': 'Income Statement',\n",
    "    'BALANCE_SHEET': 'Balance Sheet',\n",
    "    'CASH_FLOW': 'Cash Flow Statement'\n",
    "}\n",
    "\n",
    "os.makedirs(OUTPUT_PATH, exist_ok=True)\n",
    "os.makedirs(COMP_PATH, exist_ok=True)\n",
    "\n",
    "# ===========================\n",
    "# Helper functions\n",
    "# ===========================\n",
    "\n",
    "def get_financial_data(symbol, function, retries=5, sleep_time=20):\n",
    "    url = \"https://www.alphavantage.co/query\"\n",
    "    params = {\"function\": function, \"symbol\": symbol, \"apikey\": API_KEY}\n",
    "\n",
    "    for attempt in range(1, retries + 1):\n",
    "        response = requests.get(url, params=params)\n",
    "\n",
    "        if response.status_code != 200:\n",
    "            time.sleep(sleep_time)\n",
    "            continue\n",
    "\n",
    "        data = response.json()\n",
    "\n",
    "        if \"Note\" in data or \"Information\" in data:\n",
    "            time.sleep(sleep_time)\n",
    "            continue\n",
    "\n",
    "        if \"quarterlyReports\" in data:\n",
    "            return data[\"quarterlyReports\"][:20]\n",
    "\n",
    "        time.sleep(sleep_time)\n",
    "\n",
    "    return []\n",
    "\n",
    "def create_dataframe(reports, statement_name):\n",
    "    df = pd.DataFrame()\n",
    "    for report in reports:\n",
    "        fiscal_date = pd.to_datetime(report.get('fiscalDateEnding')).strftime('%Y-%m-%d')\n",
    "        df_quarter = pd.DataFrame.from_dict(report, orient='index')\n",
    "        df_quarter.columns = [fiscal_date]\n",
    "        df_quarter.index.name = statement_name\n",
    "        df = pd.concat([df, df_quarter], axis=1)\n",
    "    return df\n",
    "\n",
    "def clean_dynamic_df(df):\n",
    "    df.columns = [str(c).split(\".\")[0] for c in df.columns]\n",
    "    df = df.groupby(df.columns, axis=1).first()\n",
    "\n",
    "    df.reset_index(inplace=True)\n",
    "    df.rename(columns={'index': 'Line Item'}, inplace=True)\n",
    "\n",
    "    if 'Line Item' in df.columns:\n",
    "        df = df[df['Line Item'] != 'fiscalDateEnding']\n",
    "\n",
    "    data = {\n",
    "        'Line Item': df.iloc[:, 0].tolist(),\n",
    "        **df.iloc[:, 1:].sort_index(axis=1, ascending=False).to_dict(orient='list')\n",
    "    }\n",
    "\n",
    "    df_dynamic = pd.DataFrame(data)\n",
    "    df_dynamic.set_index('Line Item', inplace=True)\n",
    "    return df_dynamic\n",
    "\n",
    "def get_company_overview(symbol, retries=5, sleep_time=12):\n",
    "    url = 'https://www.alphavantage.co/query'\n",
    "    params = {'function': 'OVERVIEW', 'symbol': symbol, 'apikey': API_KEY}\n",
    "\n",
    "    for attempt in range(1, retries + 1):\n",
    "        response = requests.get(url, params=params)\n",
    "\n",
    "        if response.status_code != 200:\n",
    "            time.sleep(sleep_time)\n",
    "            continue\n",
    "\n",
    "        data = response.json()\n",
    "\n",
    "        if \"Note\" in data or \"Information\" in data:\n",
    "            time.sleep(sleep_time)\n",
    "            continue\n",
    "\n",
    "        if data:\n",
    "            df = pd.DataFrame.from_dict(data, orient='index', columns=['Value'])\n",
    "            df.index.name = 'Attribute'\n",
    "            return df\n",
    "\n",
    "        time.sleep(sleep_time)\n",
    "\n",
    "    return None\n",
    "\n",
    "def process_ticker(ticker):\n",
    "    combined_df = pd.DataFrame()\n",
    "\n",
    "    for func, name in STATEMENTS.items():\n",
    "        reports = get_financial_data(ticker, func)\n",
    "        if reports:\n",
    "            df_section = create_dataframe(reports, name)\n",
    "            combined_df = pd.concat([combined_df, df_section], axis=1)\n",
    "\n",
    "    if not combined_df.empty:\n",
    "        df_clean = clean_dynamic_df(combined_df)\n",
    "        output_file = os.path.join(OUTPUT_PATH, f\"df_{ticker}.xlsx\")\n",
    "        df_clean.to_excel(output_file, index=True)\n",
    "\n",
    "    company_df = get_company_overview(ticker)\n",
    "    if company_df is not None:\n",
    "        out_file = os.path.join(COMP_PATH, f\"CD_{ticker}.xlsx\")\n",
    "        company_df.to_excel(out_file, index=True)\n",
    "\n",
    "if __name__ == \"__main__\":\n",
    "\n",
    "    with open(TICKERS_FILE, \"r\") as f:\n",
    "        tickers = [line.strip().upper() for line in f if line.strip()]\n",
    "\n",
    "    for ticker in tickers:\n",
    "        try:\n",
    "            process_ticker(ticker)\n",
    "            time.sleep(12)\n",
    "        except Exception as e:\n",
    "            print(f\"Error processing {ticker}: {e}\")\n"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": 9,
   "id": "5eb5d856",
   "metadata": {},
   "outputs": [
    {
     "name": "stdout",
     "output_type": "stream",
     "text": [
      "\n",
      "==============================\n",
      "📈 Running for ticker: CVI\n",
      "==============================\n",
      "CVI: 📄 Dividend file saved to /Users/andras/OneDrive/Fundamentals/MoreComp/Dividend/Div_CVI.xlsx\n"
     ]
    }
   ],
   "source": [
    "DIVIDEND_PATH = os.path.join(BASE_PATH, \"Dividend\")\n",
    "os.makedirs(DIVIDEND_PATH, exist_ok=True)\n",
    "\n",
    "def export_dividends(ticker):\n",
    "    timezone = 'America/New_York'\n",
    "    today = pd.Timestamp.now(tz=pytz.timezone(timezone)).normalize()\n",
    "\n",
    "    series = yf.Ticker(ticker).dividends\n",
    "\n",
    "    if not series.empty:\n",
    "        series = series.sort_index(ascending=False)\n",
    "        dfdi = (\n",
    "            series.to_frame(name='Dividend')\n",
    "            .reset_index()\n",
    "            .rename(columns={'index': 'Date'})\n",
    "        )\n",
    "        dfdi['Date'] = pd.to_datetime(dfdi['Date']).dt.tz_localize(None)\n",
    "        data = dfdi[['Date', 'Dividend']].copy()\n",
    "    else:\n",
    "        first_date = BMonthEnd().rollback(today)\n",
    "        dates = []\n",
    "        for i in range(20):\n",
    "            candidate = first_date - pd.DateOffset(months=3 * i)\n",
    "            candidate_bme = BMonthEnd().rollback(candidate)\n",
    "            dates.append(candidate_bme.normalize())\n",
    "        data = pd.DataFrame({'Date': dates, 'Dividend': 1})\n",
    "\n",
    "    data['Date'] = pd.to_datetime(data['Date']).dt.strftime('%Y-%m-%d')\n",
    "    data = data.sort_values('Date', ascending=False).reset_index(drop=True)\n",
    "\n",
    "    out_file = os.path.join(DIVIDEND_PATH, f\"Div_{ticker}.xlsx\")\n",
    "    data.to_excel(out_file, index=False)\n",
    "\n",
    "# Run dividends after financials\n",
    "for ticker in tickers:\n",
    "    try:\n",
    "        export_dividends(ticker)\n",
    "    except Exception as e:\n",
    "        print(f\"Error processing {ticker}: {e}\")"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": null,
   "id": "297ca137",
   "metadata": {},
   "outputs": [],
   "source": []
  }
 ],
 "metadata": {
  "kernelspec": {
   "display_name": "Python 3",
   "language": "python",
   "name": "python3"
  },
  "language_info": {
   "codemirror_mode": {
    "name": "ipython",
    "version": 3
   },
   "file_extension": ".py",
   "mimetype": "text/x-python",
   "name": "python",
   "nbconvert_exporter": "python",
   "pygments_lexer": "ipython3",
   "version": "3.8.8"
  }
 },
 "nbformat": 4,
 "nbformat_minor": 5
}
