{
 "cells": [
  {
   "cell_type": "code",
   "execution_count": null,
   "id": "imports",
   "metadata": {},
   "outputs": [],
   "source": [
    "import os\n",
    "import time\n",
    "import requests\n",
    "import pandas as pd\n",
    "import numpy as np\n",
    "import yfinance as yf\n",
    "import pytz\n",
    "from datetime import datetime\n",
    "from pandas.tseries.offsets import BMonthEnd\n"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": null,
   "id": "financial_functions",
   "metadata": {},
   "outputs": [],
   "source": [
    "# ===========================\n",
    "# PATH CONFIG\n",
    "# ===========================\n",
    "BASE_PATH = './data'\n",
    "OUTPUT_PATH = os.path.join(BASE_PATH, 'Comp')\n",
    "COMP_PATH = os.path.join(BASE_PATH, 'CD')\n",
    "DIVIDEND_PATH = os.path.join(BASE_PATH, 'Dividend')\n",
    "TICKERS_FILE = './tickers.txt'\n",
    "\n",
    "os.makedirs(OUTPUT_PATH, exist_ok=True)\n",
    "os.makedirs(COMP_PATH, exist_ok=True)\n",
    "os.makedirs(DIVIDEND_PATH, exist_ok=True)\n",
    "\n",
    "# ===========================\n",
    "# API CONFIG\n",
    "# ===========================\n",
    "API_KEY = '5VJ5OHNNB582TWUU'\n",
    "STATEMENTS = {\n",
    "    'INCOME_STATEMENT': 'Income Statement',\n",
    "    'BALANCE_SHEET': 'Balance Sheet',\n",
    "    'CASH_FLOW': 'Cash Flow Statement'\n",
    "}\n",
    "\n",
    "# ===========================\n",
    "# HELPER FUNCTIONS\n",
    "# ===========================\n",
    "\n",
    "def get_financial_data(symbol, function, retries=5, sleep_time=20):\n",
    "    url = 'https://www.alphavantage.co/query'\n",
    "    params = {'function': function, 'symbol': symbol, 'apikey': API_KEY}\n",
    "    for attempt in range(retries):\n",
    "        resp = requests.get(url, params=params)\n",
    "        if resp.status_code != 200:\n",
    "            time.sleep(sleep_time)\n",
    "            continue\n",
    "        data = resp.json()\n",
    "        if 'Note' in data or 'Information' in data:\n",
    "            time.sleep(sleep_time)\n",
    "            continue\n",
    "        if 'quarterlyReports' in data:\n",
    "            return data['quarterlyReports'][:20]\n",
    "        time.sleep(sleep_time)\n",
    "    return []\n",
    "\n",
    "def create_dataframe(reports, statement_name):\n",
    "    df = pd.DataFrame()\n",
    "    for r in reports:\n",
    "        date = pd.to_datetime(r.get('fiscalDateEnding')).strftime('%Y-%m-%d')\n",
    "        dfq = pd.DataFrame.from_dict(r, orient='index')\n",
    "        dfq.columns = [date]\n",
    "        dfq.index.name = statement_name\n",
    "        df = pd.concat([df, dfq], axis=1)\n",
    "    return df\n",
    "\n",
    "def clean_dynamic_df(df):\n",
    "    df.columns = [str(c).split('.')[0] for c in df.columns]\n",
    "    df = df.groupby(df.columns, axis=1).first()\n",
    "    df.reset_index(inplace=True)\n",
    "    df.rename(columns={'index':'Line Item'}, inplace=True)\n",
    "    df = df[df['Line Item'] != 'fiscalDateEnding']\n",
    "    data = {'Line Item': df.iloc[:,0].tolist(), **df.iloc[:,1:].sort_index(axis=1, ascending=False).to_dict(orient='list')}\n",
    "    df_dyn = pd.DataFrame(data)\n",
    "    df_dyn.set_index('Line Item', inplace=True)\n",
    "    return df_dyn\n",
    "\n",
    "def get_company_overview(symbol, retries=5, sleep_time=12):\n",
    "    url = 'https://www.alphavantage.co/query'\n",
    "    params = {'function':'OVERVIEW','symbol':symbol,'apikey':API_KEY}\n",
    "    for attempt in range(retries):\n",
    "        resp = requests.get(url, params=params)\n",
    "        if resp.status_code != 200:\n",
    "            time.sleep(sleep_time)\n",
    "            continue\n",
    "        data = resp.json()\n",
    "        if 'Note' in data or 'Information' in data:\n",
    "            time.sleep(sleep_time)\n",
    "            continue\n",
    "        if data:\n",
    "            df = pd.DataFrame.from_dict(data, orient='index', columns=['Value'])\n",
    "            df.index.name = 'Attribute'\n",
    "            return df\n",
    "        time.sleep(sleep_time)\n",
    "    return None\n",
    "\n",
    "def process_ticker(ticker):\n",
    "    combined_df = pd.DataFrame()\n",
    "    for func,name in STATEMENTS.items():\n",
    "        reports = get_financial_data(ticker, func)\n",
    "        if reports:\n",
    "            df_sec = create_dataframe(reports, name)\n",
    "            combined_df = pd.concat([combined_df, df_sec], axis=1)\n",
    "    if not combined_df.empty:\n",
    "        df_clean = clean_dynamic_df(combined_df)\n",
    "        df_clean.to_excel(os.path.join(OUTPUT_PATH, f'df_{ticker}.xlsx'))\n",
    "    comp_df = get_company_overview(ticker)\n",
    "    if comp_df is not None:\n",
    "        comp_df.to_excel(os.path.join(COMP_PATH, f'CD_{ticker}.xlsx'))"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": null,
   "id": "dividends",
   "metadata": {},
   "outputs": [],
   "source": [
    "def export_dividends(ticker):\n",
    "    today = pd.Timestamp.now(tz=pytz.timezone('America/New_York')).normalize()\n",
    "    series = yf.Ticker(ticker).dividends\n",
    "    if not series.empty:\n",
    "        dfdi = series.sort_index(ascending=False).to_frame(name='Dividend').reset_index()\n",
    "        dfdi.rename(columns={'index':'Date'}, inplace=True)\n",
    "        dfdi['Date'] = pd.to_datetime(dfdi['Date']).dt.tz_localize(None)\n",
    "        data = dfdi[['Date','Dividend']]\n",
    "    else:\n",
    "        first_date = BMonthEnd().rollback(today)\n",
    "        dates = []\n",
    "        for i in range(20):\n",
    "            candidate = first_date - pd.DateOffset(months=3*i)\n",
    "            candidate_bme = BMonthEnd().rollback(candidate)\n",
    "            dates.append(candidate_bme.normalize())\n",
    "        data = pd.DataFrame({'Date':dates,'Dividend':1})\n",
    "    data['Date'] = pd.to_datetime(data['Date']).dt.strftime('%Y-%m-%d')\n",
    "    data.sort_values('Date', ascending=False, inplace=True)\n",
    "    data.reset_index(drop=True, inplace=True)\n",
    "    data.to_excel(os.path.join(DIVIDEND_PATH, f'Div_{ticker}.xlsx'), index=False)\n",
    "\n",
    "if __name__ == '__main__':\n",
    "    with open(TICKERS_FILE,'r') as f:\n",
    "        tickers = [line.strip().upper() for line in f if line.strip()]\n",
    "    for ticker in tickers:\n",
    "        try:\n",
    "            process_ticker(ticker)\n",
    "            export_dividends(ticker)\n",
    "            time.sleep(12)\n",
    "        except Exception as e:\n",
    "            print(f'Error processing {ticker}: {e}')"
   ]
  }
 ],
 "metadata": {
  "kernelspec": {
   "display_name": "Python 3",
   "language": "python",
   "name": "python3"
  },
  "language_info": {
   "name": "python",
   "version": "3.11"
  }
 },
 "nbformat": 4,
 "nbformat_minor": 5
}
